---
- name: Load host facts for role use
  ansible.builtin.set_fact:
    regolith_distribution: "{{ ansible_facts.distribution }}"
    regolith_distribution_release: "{{ ansible_facts.distribution_release }}"
    regolith_os_family: "{{ ansible_facts.os_family }}"
    regolith_detected_architecture: "{{ ansible_facts.architecture }}"
