---
- name: Prepare instances for Ansible and tests
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Install packages required for role execution
      ansible.builtin.apt:
        name:
          - python3
          - python3-apt
          - gnupg
        update_cache: true
        state: present
