---
role_name_check: 1

driver:
  name: vagrant

platforms:
  - name: regolith-vagrant
    box: "bento/ubuntu-24.04"
    hostname: regolith-vagrant
    interfaces:
      - network_name: private_network
        type: static
        ip: 192.168.56.30
    memory: 4096
    cpus: 2

provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_ssh_common_args: "-F /dev/null -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
  inventory:
    links:
      hosts: ../../inventory/${MOLECULE_VAGRANT_INVENTORY:-vagrant.yml}
  playbooks:
    create: create.yml
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml
    destroy: destroy.yml

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
