# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  machine_name = "regolith-vagrant"
  memory = 4096
  cpus = 2

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.define machine_name do |node|
    node.vm.hostname = machine_name
    node.vm.box = "bento/ubuntu-24.04"
    node.vm.box_check_update = false

    node.vm.provider "virtualbox" do |v, o|
      v.memory = memory
      v.cpus = cpus
      v.gui = false
      v.customize ["modifyvm", :id, "--vram", "128"]
      o.vm.network "private_network",
                   ip: "192.168.56.30",
                   netmask: "255.255.255.0",
                   auto_config: true
    end

    if Vagrant.has_plugin?("vagrant-libvirt")
      node.vm.provider "libvirt" do |l, o|
        l.memory = memory
        l.cpus = cpus
        l.driver = "kvm"
        l.video_type = "virtio"
        l.video_vram = 128
        o.vm.network "private_network",
                     ip: "192.168.121.30",
                     netmask: "255.255.255.0",
                     auto_config: true,
                     libvirt__network_name: "vagrant-56",
                     libvirt__mgmt_network: "none"
      end
    end

    node.vm.provision "shell",
                      inline: "date | tee /etc/vagrant_provisioned_at && ip -4 addr show || true",
                      privileged: true

    node.trigger.after :destroy do |trigger|
      trigger.info = "Removing known_hosts entry for #{machine_name}"
      trigger.on_error = :continue
      trigger.run = { inline: "ssh-keygen -R #{machine_name}" }
    end
  end
end
