---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: instance
    connection_options:
      ansible_connection: local
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
verifier:
  name: ansible
scenario:
  name: unit-ubuntu-plucky
  test_sequence:
    - syntax
    - converge
