---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian-bookworm
    image: debian:bookworm
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      ansible_become: false
  playbooks:
    converge: ../common/converge.yml
    prepare: ../common/docker_prepare.yml
    verify: ../default/verify.yml
verifier:
  name: ansible
scenario:
  name: debian-bookworm
  test_sequence:
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
